Algoritmo "semnome"
//  
//  
// 3. Fazer um algoritmo que:
//• Leia um número indeterminado de linhas
//contendo cada uma a idade de um indivíduo.
//• A última linha que não entrará nos cálculos,
//contém o valor da idade igual a zero.
//• Calcule e escreva a idade média deste grupo
//de indivíduos.
//• Escreva também a maior idade e a menor
Var
id, n: inteiro
soma, media: real

Inicio
soma := 0
n := 0

para id  faca
     se id


Fimalgoritmo