Algoritmo "TesteParaFaca"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/1/2020
Var
// Seção de Declarações das variáveis 
i, soma: inteiro

Inicio
soma <- 0

para i de 2 ate 200 passo 1 faca
     se (i % 2 = 0) entao
     soma <- soma + i
     fimse
fimpara

escreval(soma)
escreval("FIM")

Fimalgoritmo